spring:
  cloud:
    stream:
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                username: ad
                password: pw
      bindings:
        input:
          destination: queue.stream.name
          binders: local_rabbit
        output:
          destination: queue.stream.person
          binders: local_rabbit